[package]
name = "json_cli"
version = "0.0.1"
authors = ["peakchen90 <1558267774@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = { path = "../json" }